- hosts: all
  become: yes
  name: installing packages,building and containerize the application
  tasks:
    - name: updating the machine
      apt:
        upgrade: dist
        update_cache: yes
    - name: Installing and docker
      apt:
        name: docker.io
    - name: Deploy Docker Container
      command: docker run -itd --name capstone01 -p 8084:8081 malay442/sa-banking:1.0 

    - name: getting node exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz
        tar -xvf node_exporter-1.8.2.linux-amd64.tar.gz
        cd node_exporter-1.8.2.linux-amd64
        nohup ./node_exporter > /dev/null 2>&1 &

    - name: Download prometheus.yml from the repo
      get_url:
        url: https://raw.githubusercontent.com/lax66/star-agile-banking-finance_CAP01/master/prometheus.yml
        dest: /home/ubuntu/prometheus.yml
    
    - name: run prometheus container
      command: docker run -d -p 9090:9090 --name prometheus -v /home/ubuntu/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus

    - name: run grafana container
      command: docker run -d -p 3000:3000 --name grafana grafana/grafana
